version: '3.1'

services:
  database:
    image: postgres
    env_file:
      - database.env
    restart: always
    ports:
    - "5433:5432"
    expose:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    env_file:
      - metabase.env
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - metabase-data:/var/lib/metabase/data

volumes:
  metabase-data:
  database-data: