server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/mnt/data/files/java-school-project
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

my:
  generation: true

  kafka:
    compressionType: zstd
    topicName: orders
    bootstrapAddress: localhost:9092
  multiThreadScheduled:
    threads: 4
