server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testdatabase
    username: testuser
    password: testpass

  jpa:
    hibernate:
      ddl-auto: update

my:
  generation: true

  kafka:
    compressionType: zstd
    topicName: orders
    bootstrapAddress: localhost:9092
  multiThreadScheduled:
    threads: 4
